# Generated by Django 3.2 on 2021-07-21 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_category_name', models.CharField(blank=True, max_length=255, verbose_name='Nom categorie')),
                ('hotel_decription', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Categorie hotel',
                'verbose_name_plural': 'Categories hotels',
                'ordering': ['hotel_category_name'],
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_category_name', models.CharField(blank=True, max_length=255, verbose_name='Nom categorie')),
                ('hotel_decription', models.TextField(verbose_name='Description chambre')),
            ],
            options={
                'verbose_name': 'Categorie chambre',
                'verbose_name_plural': 'Categories chambres',
                'ordering': ['room_category_name'],
            },
        ),
        migrations.CreateModel(
            name='RoomHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=255, verbose_name='Nom chambre')),
                ('room_number', models.IntegerField(blank=True, verbose_name='Numero chambre')),
                ('room_capacity', models.IntegerField(blank=True, verbose_name='Capacité')),
                ('hotel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotelapp.roomcategory', verbose_name='Categorie chambre')),
            ],
            options={
                'verbose_name': 'Chambre hotel',
                'verbose_name_plural': 'Chambres hotels',
                'ordering': ['room_name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('hotel_address', models.CharField(blank=True, max_length=255, verbose_name='Addresse')),
                ('hotel_categry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotelapp.hotelcategory', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['hotel_name'],
            },
        ),
    ]
