# Generated by Django 3.2 on 2021-07-22 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now=True, verbose_name='Date_heure du pan de servation')),
                ('start_date', models.DateTimeField(auto_now=True, verbose_name="Date d'arrivée")),
                ('end_date', models.DateTimeField(auto_now=True, verbose_name='Date de sortie')),
                ('child_count', models.IntegerField(blank=True, verbose_name='Nombre des personnes')),
                ('discount_coupe', models.IntegerField(blank=True, verbose_name='Montant de reduction')),
                ('total_cost', models.IntegerField(blank=True, verbose_name='Total prix')),
                ('payement_amount', models.IntegerField(blank=True, verbose_name='Montant à payer')),
                ('payement_type', models.IntegerField(blank=True, verbose_name='Type de payement')),
                ('is_block', models.IntegerField(blank=True, verbose_name='plan de reservation bloqué')),
                ('is_delete', models.IntegerField(blank=True, verbose_name='plan de reservation supprimé')),
            ],
            options={
                'verbose_name': 'Plan reservation',
                'verbose_name_plural': 'Plans de reservations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(blank=True, upload_to='hotel_image/'),
        ),
        migrations.AddField(
            model_name='roomhotel',
            name='room_image',
            field=models.ImageField(blank=True, upload_to='room_image/'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('booking_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotelapp.bookingroom', verbose_name='Chambre')),
                ('room_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotelapp.roomhotel', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['room_name'],
            },
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True, verbose_name='Date debut')),
                ('end_date', models.DateTimeField(auto_now=True, verbose_name='Date de fin')),
                ('sun', models.CharField(blank=True, max_length=50, verbose_name='Dimanche')),
                ('mon', models.CharField(blank=True, max_length=50, verbose_name='Lundi')),
                ('tue', models.CharField(blank=True, max_length=50, verbose_name='Mardi')),
                ('Wed', models.CharField(blank=True, max_length=50, verbose_name='Mercredi')),
                ('thu', models.CharField(blank=True, max_length=50, verbose_name='Jeudi')),
                ('fri', models.CharField(blank=True, max_length=50, verbose_name='Vendredi')),
                ('sat', models.CharField(blank=True, max_length=50, verbose_name='Samedi')),
                ('description', models.TextField()),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotelapp.roomcategory', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Plan de prix',
                'verbose_name_plural': 'Plans de prix',
                'ordering': ['room_type'],
            },
        ),
    ]
