# Generated by Django 3.2 on 2021-07-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_auto_20210722_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceplan',
            old_name='Wed',
            new_name='Wed_d',
        ),
        migrations.RenameField(
            model_name='priceplan',
            old_name='fri',
            new_name='fri_d',
        ),
        migrations.RenameField(
            model_name='priceplan',
            old_name='mon',
            new_name='mon_d',
        ),
        migrations.RenameField(
            model_name='priceplan',
            old_name='sat',
            new_name='sat_d',
        ),
        migrations.RenameField(
            model_name='priceplan',
            old_name='sun',
            new_name='sun_d',
        ),
        migrations.RenameField(
            model_name='priceplan',
            old_name='thu',
            new_name='thu_d',
        ),
        migrations.RenameField(
            model_name='priceplan',
            old_name='tue',
            new_name='tue_d',
        ),
    ]
