# Generated by Django 3.2 on 2021-08-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_auto_20210722_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='phone')),
                ('sexe', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=255, null=True, verbose_name='genre')),
                ('profile_pic', models.ImageField(blank=True, default='profile2.png', null=True, upload_to='profil/')),
                ('type_user', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('image_profil', models.ImageField(default='profile1.png', null=True, upload_to='')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utilisatur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hotelapp.usermodel')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
            bases=('hotelapp.usermodel',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hotelapp.usermodel')),
                ('regularite', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': '-Client',
                'verbose_name_plural': '- Clients',
                'ordering': ['regularite'],
            },
            bases=('hotelapp.usermodel',),
        ),
    ]
